In [83]:
%%writefile CountryNameCode.csv
malaysia
japan
india
china
thailand
vietnam
cambodia
singapore
indonesia
canada
united_states
united_kingdom
germany
france
italy
spain
philippines
south_korea
mexico
austria
poland
portugal
egypt
denmark
australia
cambodia
belgium
sudan
russia
norway
saudi_arabia

Overwriting CountryNameCode.csv

In [141]:
from selenium import webdriver
from bs4 import BeautifulSoup
import urllib.request
import re   
import time
import numpy as np
import pandas
import csv

word = '</strong>'
num = 2

class population_crawling: 
    
    def median_age():
        with open('median_age.csv', 'w', encoding='UTF-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow( ['country name', 'total','male', 'female'] )

            pf= pandas.read_csv('CountryNameCode.csv', engine='python')

            for i in range(16):

                mtitle=pf[pf.columns[0]].iloc[i]


                url='https://www.indexmundi.com/'+str(mtitle)+'/demographics_profile.html'

                print(url)
                total = re.compile(r'.<strong>total: </strong>(.*)<br/><strong>male.*') 
                male=re.compile(r'.<strong>male: </strong>(.*)<br/><strong>female.*')
                female=re.compile(r'.<strong>female: </strong>(.*)<br/>.*')

                driver=webdriver.Chrome("C:/Users/ATIV/Downloads/chromedriver_win32/chromedriver")
                driver.get(url)
                soup = BeautifulSoup(driver.page_source, "html.parser")


                link = soup.find_all("div", {"class":"col-md-8 c"})
                print("===================================")

                for posts in link:
                    time.sleep(0.33)
                    z=str(posts)
                    zz=str(posts).split(' ')
                    #print(str(zz))
                    str_index=0
                    count = 0
                    for aaa in zz:
                        #index = 0
                        str_index+=len(aaa)
                        if word in aaa:  
                            count+=1
                            if(count == num):

                                #index=aaa.find(word[len(word)-1])
                                #print(z[str_index-len(aaa)+len(word):])                #search word가 붙어있을 경우     ex) </strong>12.84%
                                #print(z[str_index:])                                    #search word가 띄어져 있을 경우  ex) </strong> 12.84%
                                break
                        str_index+=1

                    a=total.search(z).group(1).strip()
                    b=male.search(z).group(1).strip()
                    c=female.search(z).group(1).strip()
                    
                Field1=mtitle
                Field2=a.split()[0]
                Field3=b.split()[0]
                Field4=c.split()[0]
               
             
                writer.writerow([Field1,Field2,Field3,Field4])

    def age_structure():
        with open('age_structure.csv', 'w', encoding='UTF-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow( ['country name','0-14', '15-24', '25-54', '54-64', '65+'] )

            pf= pandas.read_csv('CountryNameCode.csv', engine='python')

            for i in range(16):

                mtitle=pf[pf.columns[0]].iloc[i]


                url='https://www.indexmundi.com/'+str(mtitle)+'/age_structure.html'

                print(url)

                Age0_14=re.compile(r'.0-14 years: </strong>(.*)<br/><strong>15.*')
                Age15_24=re.compile(r'.15-24 years: </strong>(.*)<br/><strong>25.*')
                Age25_54=re.compile(r'.25-54 years: </strong>(.*)<br/><strong>55.*')
                Age54_64=re.compile(r'.55-64 years: </strong>(.*)<br/><strong>65.*')
                Age65=re.compile(r'.65 years and over: </strong>(.*)<br/>.*')

                driver=webdriver.Chrome("C:/Users/ATIV/Downloads/chromedriver_win32/chromedriver")
                driver.get(url)
                soup = BeautifulSoup(driver.page_source, "html.parser")

                link = soup.find_all("div", {"class":"c"})
                print("===================================")

                for posts in link:
                    time.sleep(0.33)
                    z=str(posts)
                    zz=str(posts).split(' ')
                    #print(str(zz))
                    str_index=0
                    count = 0
                    for aaa in zz:
                        #index = 0
                        str_index+=len(aaa)
                        if word in aaa:  
                            count+=1
                            if(count == num):

                                #index=aaa.find(word[len(word)-1])
                                #print(z[str_index-len(aaa)+len(word):])                #search word가 붙어있을 경우     ex) </strong>12.84%
                                #print(z[str_index:])                                    #search word가 띄어져 있을 경우  ex) </strong> 12.84%
                                break
                        str_index+=1

                    a=Age0_14.search(z).group(1).strip()
                    b=Age15_24.search(z).group(1).strip()
                    c=Age25_54.search(z).group(1).strip()
                    d=Age54_64.search(z).group(1).strip()
                    e=Age65.search(z).group(1).strip()

                Field1=mtitle
                Field3=a.split()[0][:len(a.split()[0])-1]
                Field4=b.split()[0][:len(b.split()[0])-1]
                Field5=c.split()[0][:len(c.split()[0])-1]
                Field6=d.split()[0][:len(d.split()[0])-1]
                Field7=e.split()[0][:len(e.split()[0])-1]
                
             
                writer.writerow([Field1,Field3,Field4,Field5, Field6, Field7])

class economy_crawling:
    
    def Unemployment():
        with open('Unemployment.csv', 'w', encoding='UTF-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow( ['country name','2006','2007','2008','2009', '2010','2011', '2012','2013','2014'] )

            pf= pandas.read_csv('CountryNameCode.csv', engine='python')

            for i in range(10,16):

                mtitle=pf[pf.columns[0]].iloc[i]


                url='https://www.indexmundi.com/'+str(mtitle)+'/unemployment_rate.html'

                print(url)
                unemp_2006=re.compile(r'.2006</td><td>(.*)</td><td>.*') 
                unemp_2007=re.compile(r'.2007</td><td>(.*)</td><td>.*') 
                unemp_2008=re.compile(r'.2008</td><td>(.*)</td><td>.*') 
                unemp_2009=re.compile(r'.2009</td><td>(.*)</td><td>.*') 
                unemp_2010=re.compile(r'.2010</td><td>(.*)</td><td>.*') 
                unemp_2011=re.compile(r'.2011</td><td>(.*)</td><td>.*')
                unemp_2012=re.compile(r'.2012</td><td>(.*)</td><td>.*')
                unemp_2013=re.compile(r'.2013</td><td>(.*)</td><td>.*')
                unemp_2014=re.compile(r'.2014</td><td>(.*)</td><td>.*')
              
                driver=webdriver.Chrome("C:/Users/ATIV/Downloads/chromedriver_win32/chromedriver")
                driver.get(url)
                soup = BeautifulSoup(driver.page_source, "html.parser")


                link = soup.find_all("table", {"class":"tblrank"})
       
                print("===================================")

                for posts in link:
                    time.sleep(0.33)
                    z=str(posts)
                    zz=str(posts).split(' ')
                    #print(str(zz))
                    str_index=0
                    count = 0
                    for aaa in zz:
                        #index = 0
                        str_index+=len(aaa)
                        if word in aaa:  
                            count+=1
                            if(count == num):

                                #index=aaa.find(word[len(word)-1])
                                #print(z[str_index-len(aaa)+len(word):])                #search word가 붙어있을 경우     ex) </strong>12.84%
                                #print(z[str_index:])                                    #search word가 띄어져 있을 경우  ex) </strong> 12.84%
                                break
                        str_index+=1

                    
                    a=unemp_2006.search(z).group(1).strip()
                    b=unemp_2007.search(z).group(1).strip()
                    c=unemp_2008.search(z).group(1).strip()
                    d=unemp_2009.search(z).group(1).strip()
                    e=unemp_2010.search(z).group(1).strip()
                    f=unemp_2011.search(z).group(1).strip()
                    g=unemp_2012.search(z).group(1).strip()
                    h=unemp_2013.search(z).group(1).strip()
                    i=unemp_2014.search(z).group(1).strip()
                    
                Field1=mtitle
                Field2=a.split()[0][:3]
                Field3=b.split()[0][:3]
                Field4=c.split()[0][:3]
                Field5=d.split()[0][:3]
                Field6=e.split()[0][:3]
                Field7=f.split()[0][:3]
                Field8=g.split()[0][:3]
                Field9=h.split()[0][:3]
                Field10=i.split()[0][:3]
                
             
                writer.writerow([Field1,Field2,Field3,Field4,Field5,Field6,Field7,Field8,Field9,Field10])
                
    def GDP_composition():
        with open('GDP_composition.csv', 'w', encoding='UTF-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow( ['country name', 'household consumption','government consumption', 'investment in fixed capital',\
            'investment in inventories','exports of S&G','imports of S&G'] )

            pf= pandas.read_csv('CountryNameCode.csv', engine='python')

            for i in range(16):

                mtitle=pf[pf.columns[0]].iloc[i]


                url='https://www.indexmundi.com/'+str(mtitle)+'/economy_profile.html'

                print(url)
                HS_consumption = re.compile(r'.household consumption: </strong>(.*)<br/><strong>government.*') 
                Gov_consumption=re.compile(r'.government consumption: </strong>(.*)<br/><strong>investment in fixed capital.*')
                inv_fixedcapital=re.compile(r'.investment in fixed capital: </strong>(.*)<br/><strong>investment in inventories.*')
                inv_inventories=re.compile(r'.inventories: </strong>(.*)<br/><strong>exports of goods and services.*')
                exports = re.compile(r'.exports of goods and services: </strong>(.*)<br/><strong>imports.*')
                imports = re.compile(r'.imports of goods and services: </strong>(.*)<br/>.*')

                driver=webdriver.Chrome("C:/Users/ATIV/Downloads/chromedriver_win32/chromedriver")
                driver.get(url)
                soup = BeautifulSoup(driver.page_source, "html.parser")


                link = soup.find_all("div", {"class":"col-md-8 c"})
    
                print("===================================")

                for posts in link:
                    time.sleep(0.33)
                    z=str(posts)
                    zz=str(posts).split(' ')
                    #print(str(zz))
                    str_index=0
                    count = 0
                    for aaa in zz:
                        #index = 0
                        str_index+=len(aaa)
                        if word in aaa:  
                            count+=1
                            if(count == num):

                                #index=aaa.find(word[len(word)-1])
                                #print(z[str_index-len(aaa)+len(word):])                #search word가 붙어있을 경우     ex) </strong>12.84%
                                #print(z[str_index:])                                    #search word가 띄어져 있을 경우  ex) </strong> 12.84%
                                break
                        str_index+=1

                    a=HS_consumption.search(z).group(1).strip()
                    b=Gov_consumption.search(z).group(1).strip()
                    c=inv_fixedcapital.search(z).group(1).strip()
                    d=inv_inventories.search(z).group(1).strip()
                    e=exports.search(z).group(1).strip()
                    f=imports.search(z).group(1).strip()
                    
                Field1=mtitle
                Field2=a.split()[0][:len(a.split()[0])-1]
                Field3=b.split()[0][:len(b.split()[0])-1]
                Field4=c.split()[0][:len(c.split()[0])-1]
                Field5=d.split()[0][:len(d.split()[0])-1]
                Field6=e.split()[0][:len(e.split()[0])-1]
                Field7=f.split()[0][:len(f.split()[0])-1]
               
             
                writer.writerow([Field1,Field2,Field3,Field4,Field5,Field6,Field7])

In [131]:
def CheckTime(func):
    import time

    def newFunc(*args, **kwargs):
        start = time.time()
        func(*args, **kwargs)
        end = time.time()
        
        print("\n실행시간 : ",end - start)

    return newFunc

In [132]:
class WrongStudentRecord(Exception):
    def __init__(self, msg):
        self._message = msg

In [142]:
@CheckTime
def get_population():
    population_crawling.age_structure()
    population_crawling.median_age()

@CheckTime
def get_Unemp():  
    try: 
        economy_crawling.Unemployment()
    except AttributeError:
        pass
        
    except IndexError:
        raise WrongStudentRecord("CountryNameCode.csv 파일의 나라 갯수를 다시 확인해주세요")
    
    except:
        pass 


@CheckTime
def get_GDP():
    try:
        economy_crawling.GDP_composition()
    except:
        raise WrongStudentRecord("에러가 발생했습니다. 크롤링을 다시 시작해주세요")

In [87]:
get_population()

https://www.indexmundi.com/japan/age_structure.html
===================================
https://www.indexmundi.com/india/age_structure.html
===================================
https://www.indexmundi.com/china/age_structure.html
===================================
https://www.indexmundi.com/thailand/age_structure.html
===================================
https://www.indexmundi.com/vietnam/age_structure.html
===================================
https://www.indexmundi.com/cambodia/age_structure.html
===================================
https://www.indexmundi.com/singapore/age_structure.html
===================================
https://www.indexmundi.com/indonesia/age_structure.html
===================================
https://www.indexmundi.com/canada/age_structure.html
===================================
https://www.indexmundi.com/united_states/age_structure.html
===================================
https://www.indexmundi.com/united_kingdom/age_structure.html
===================================
https://www.indexmundi.com/germany/age_structure.html
===================================
https://www.indexmundi.com/france/age_structure.html
===================================
https://www.indexmundi.com/spain/age_structure.html
===================================
https://www.indexmundi.com/philippines/age_structure.html
===================================
https://www.indexmundi.com/south_korea/age_structure.html
===================================
https://www.indexmundi.com/japan/demographics_profile.html
===================================
https://www.indexmundi.com/india/demographics_profile.html
===================================
https://www.indexmundi.com/china/demographics_profile.html
===================================
https://www.indexmundi.com/thailand/demographics_profile.html
===================================
https://www.indexmundi.com/vietnam/demographics_profile.html
===================================
https://www.indexmundi.com/cambodia/demographics_profile.html
===================================
https://www.indexmundi.com/singapore/demographics_profile.html
===================================
https://www.indexmundi.com/indonesia/demographics_profile.html
===================================
https://www.indexmundi.com/canada/demographics_profile.html
===================================
https://www.indexmundi.com/united_states/demographics_profile.html
===================================
https://www.indexmundi.com/united_kingdom/demographics_profile.html
===================================
https://www.indexmundi.com/germany/demographics_profile.html
===================================
https://www.indexmundi.com/france/demographics_profile.html
===================================
https://www.indexmundi.com/spain/demographics_profile.html
===================================
https://www.indexmundi.com/philippines/demographics_profile.html
===================================
https://www.indexmundi.com/south_korea/demographics_profile.html
===================================

실행시간 :  476.10273122787476

In [107]:
get_GDP()

https://www.indexmundi.com/japan/economy_profile.html
===================================
https://www.indexmundi.com/india/economy_profile.html
===================================
https://www.indexmundi.com/china/economy_profile.html
===================================
https://www.indexmundi.com/thailand/economy_profile.html
===================================
https://www.indexmundi.com/vietnam/economy_profile.html
===================================
https://www.indexmundi.com/cambodia/economy_profile.html
===================================
https://www.indexmundi.com/singapore/economy_profile.html
===================================
https://www.indexmundi.com/indonesia/economy_profile.html
===================================
https://www.indexmundi.com/canada/economy_profile.html
===================================
https://www.indexmundi.com/united_states/economy_profile.html
===================================
https://www.indexmundi.com/united_kingdom/economy_profile.html
===================================
https://www.indexmundi.com/germany/economy_profile.html
===================================
https://www.indexmundi.com/france/economy_profile.html
===================================
https://www.indexmundi.com/spain/economy_profile.html
===================================
https://www.indexmundi.com/philippines/economy_profile.html
===================================
https://www.indexmundi.com/south_korea/economy_profile.html
===================================

실행시간 :  190.39374160766602

In [109]:
get_Unemp()

https://www.indexmundi.com/japan/economy_profile.html
===================================
https://www.indexmundi.com/india/economy_profile.html
===================================
https://www.indexmundi.com/china/economy_profile.html
===================================
https://www.indexmundi.com/thailand/economy_profile.html
===================================
https://www.indexmundi.com/vietnam/economy_profile.html
===================================
https://www.indexmundi.com/cambodia/economy_profile.html
===================================
https://www.indexmundi.com/singapore/economy_profile.html
===================================
https://www.indexmundi.com/indonesia/economy_profile.html
===================================
https://www.indexmundi.com/canada/economy_profile.html
===================================
https://www.indexmundi.com/united_states/economy_profile.html
===================================
https://www.indexmundi.com/united_kingdom/economy_profile.html
===================================
https://www.indexmundi.com/germany/economy_profile.html
===================================
https://www.indexmundi.com/france/economy_profile.html
===================================
https://www.indexmundi.com/spain/economy_profile.html
===================================
https://www.indexmundi.com/philippines/economy_profile.html
===================================
https://www.indexmundi.com/south_korea/economy_profile.html
===================================

실행시간 :  198.08774328231812

In [143]:
get_Unemp()

https://www.indexmundi.com/united_kingdom/unemployment_rate.html
===================================
https://www.indexmundi.com/germany/unemployment_rate.html
===================================
https://www.indexmundi.com/france/unemployment_rate.html
===================================
https://www.indexmundi.com/spain/unemployment_rate.html
===================================
https://www.indexmundi.com/philippines/unemployment_rate.html
===================================
https://www.indexmundi.com/south_korea/unemployment_rate.html
===================================

실행시간 :  85.49144077301025

In [148]:
import pandas as pd
print("________age_structure by country_________")
age_structure = pd.read_csv("age_structure.csv") 
age_structure

________age_structure by country_________

      country name   0-14  15-24  25-54  54-64    65+
0            japan  12.84   9.64  37.50  12.15  27.87
1            india  27.34  17.90  41.08   7.45   6.24
2            china  17.15  12.78  48.51  10.75  10.81
3         thailand  16.93  14.17  46.32  12.00  10.58
4          vietnam  23.55  16.23  45.56   8.55   6.12
5         cambodia  31.01  18.36  40.68   5.69   4.25
6        singapore  12.82  16.56  50.53  10.46   9.63
7        indonesia  25.02  16.99  42.40   8.58   7.01
8           canada  15.44  11.85  39.99  14.10  18.63
9    united_states  18.73  13.27  39.45  12.91  15.63
10  united_kingdom  17.53  11.90  40.55  11.98  18.04
11         germany  12.82  10.09  40.45  14.58  22.06
12          france  18.53  11.79  37.78  12.42  19.48
13           spain  15.38   9.58  44.91  12.14  17.98
14     philippines  33.39  19.16  36.99   5.97   4.49
15     south_korea  13.21  12.66  45.52  14.49  14.12

In [149]:
median_age = pd.read_csv("median_age.csv") 
print("________median_age by country_________")
median_age

________median_age by country_________

      country name  total  male  female
0            japan   47.3  46.0    48.7
1            india   27.9  27.2    28.6
2            china   37.4  36.5    38.4
3         thailand   37.7  36.6    38.7
4          vietnam   30.5  29.4    31.7
5         cambodia   25.3  24.6    26.0
6        singapore   34.6  34.5    34.7
7        indonesia   30.2  29.6    30.8
8           canada   42.2  40.9    43.5
9    united_states   38.1  36.8    39.4
10  united_kingdom   40.5  39.3    41.7
11         germany   47.1  46.0    48.2
12          france   41.4  39.6    43.1
13           spain   42.7  41.5    43.9
14     philippines   23.5  23.1    24.0
15     south_korea   41.8  40.2    43.4

In [152]:
gdp_comp = pd.read_csv("GDP_composition.csv") 
print("______________GDP Composition by country____________")
gdp_comp

______________GDP Composition by country____________

,country name,household consumption,government consumption,investment in fixed capital,investment in inventories,exports of S&G,imports of S&G
0,japan,55.9,19.5,23.5,0.2,17.8,-16.8
1,india,58.7,11.6,27.5,4.0,18.4,-20.2
2,china,39.1,14.6,43.3,1.1,19.6,-17.7
3,thailand,50.1,17.0,24.2,-7.0,70.4,-54.7
4,vietnam,68.5,6.6,24.8,2.9,98.6,-101.4
5,cambodia,76.4,5.4,22.0,0.9,62.8,-67.4
6,singapore,34.7,11.4,23.5,1.9,179.2,-150.6
7,indonesia,57.5,8.9,32.1,0.7,19.2,-18.4
8,canada,58.1,20.9,22.8,0.3,31.4,-33.6
9,united_states,69.1,17.2,16.3,0.3,12.2,-15.1
10,united_kingdom,65.3,19.0,16.6,0.7,30.1,-31.7
11,germany,53.7,19.9,20.1,-1.0,47.3,-40.0
12,france,54.8,23.5,22.0,1.3,30.3,-32.0
13,spain,57.3,18.5,19.8,0.4,34.2,-30.2
14,philippines,72.7,10.9,25.2,-0.2,32.1,-40.7
15,south_korea,47.8,15.2,29.4,0.3,43.9,-36.7

In [153]:
unemployment = pd.read_csv("Unemployment.csv") 
print("______________Unemployment by country____________")
unemployment

______________Unemployment by country____________

     country name  2006  2007  2008  2009  2010  2011  2012  2013  2014
0  united_kingdom   5.4   5.3   5.7   7.6   7.9   8.1   7.9   7.6   6.2
1         germany  10.0   8.5   7.3   7.6   6.9   5.8   5.3   5.2   4.9
2          france   8.8   8.0   7.4   9.0   9.2   9.2   9.8  10.0  10.0
3           spain   8.4   8.2  11.0  17.0  19.0  21.0  24.0  26.0  24.0
4     philippines   7.9   7.3   7.4   7.4   7.3   7.0   6.9   7.0   6.8
5     south_korea   3.4   3.2   3.1   3.6   3.7   3.4   3.2   3.1   3.5